
services:
  # Service 1: Web Server (Apache + PHP)
  web:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: my_web_server
    ports:
      - "8082:80"  # Akses project dari http://localhost:8082 di browser
    volumes:
      - .:/var/www/html # Mapping folder 'public' kita ke web root Apache
    depends_on:
      - db           # Pastikan 'db' nyala dulu sebelum 'web'
    environment:
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  # Service 2: Database (MySQL)
  db:
    image: mysql:8.0
    container_name: my_database_server
    ports:
      - "3307:3306" # Opsional: jika Anda ingin akses DB dari luar (mis: DBeaver)
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql # Menyimpan data database secara permanen

volumes:
  db_data: # Mendefinisikan volume untuk data persistence