# 1. Mulai dari image PHP + Apache
FROM php:8.2-apache

# 2. Install dependensi sistem untuk Composer dan ekstensi PHP
RUN apt-get update && apt-get install -y \
    git \
    unzip \
    libzip-dev \
    && docker-php-ext-install pdo_mysql zip \
    && a2enmod rewrite \
    && rm -rf /var/lib/apt/lists/*

# 3. Install Composer resmi dari image composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# 4. Set working directory
WORKDIR /var/www/html

# 5. Buat file composer.json dan install PHPMailer langsung
# RUN composer require phpmailer/phpmailer
# RUN composer require vlucas/phpdotenv

# salin file depedensi
COPY composer.json composer.lock ./
#langsung install aja kalo udah ada composer.json dan composer.lock
RUN composer install --no-interaction --no-scripts --no-dev --optimize-autoloader

# 6. (Opsional) Salin kode aplikasi kamu
COPY . .

# 7. (Opsional) Set permission file
# RUN chown -R www-data:www-data /var/www/html
WORKDIR /var/www/html
RUN sed -i 's|/var/www/html|/var/www/html/public|g' /etc/apache2/sites-available/000-default.conf
